echo Building Java Class...
hadoop com.sun.tools.javac.Main WordCount.java
echo Compiling into JAR...
jar -cf wc.jar WordCount*.class
echo Clearing output directory...
rm -r output/
echo Running Hadoop...
hadoop jar wc.jar WordCount input output 5
